### ISSUE TITLE
Project Resource and DataSource Support

### ISSUE THREAD

**Issue by danquack** [cloudtamer-io/terraform-provider-cloudtamerio#12]
Please answer these questions when submitting your feature request. Thanks!

Are you experiencing a problem or an inefficiency? If so, describe it.
n/a

What solution would you propose?
Create an Project resource and/or data lookup.

List any alternatives you've already tried that didn't work.
N/A

Any other information or screenshots you'd like to provide?

**Comment by danquack** [comment]
Project support won't be able to be added until the ability to migrate owners/owner groups, as well as funding source ids on the v3 api.

**Comment by josephspurrier** [comment]
Thanks Dan, I added a ticket internally for this.

**Comment by josephspurrier** [comment]
Migrated to: https://github.com/kionsoftware/terraform-provider-kion/issues/3
