### ISSUE TITLE
Data source: Users

### ISSUE THREAD

**Issue by tlgevers** [cloudtamer-io/terraform-provider-cloudtamerio#18]
Please answer these questions when submitting your feature request. Thanks!

1. Are you experiencing a problem or an inefficiency? If so, describe it.
No

2. What solution would you propose?
A data source to provide users that are currently within cloudtamer

3. List any alternatives you've already tried that didn't work.
None, just experimented with the API and it is currently supported
https://cloudtamer.foo.com/swagger/#/user

4. Any other information or screenshots you'd like to provide?
![image](https://user-images.githubusercontent.com/10062953/136240321-abd0b7a9-f71e-4bbb-8d54-c7dbef7b6887.png)

**Comment by josephspurrier** [comment]
Migrated to: https://github.com/kionsoftware/terraform-provider-kion/issues/1
