### ISSUE TITLE
Compliance Standard Support

### ISSUE THREAD

**Issue by danquack** [cloudtamer-io/terraform-provider-cloudtamerio#6]
Please answer these questions when submitting your feature request. Thanks!

Are you experiencing a problem or an inefficiency? If so, describe it.
n/a

What solution would you propose?
Create compliance standard resource and/or data lookup.

List any alternatives you've already tried that didn't work.
Currently just hard coding the IDs

Any other information or screenshots you'd like to provide?

**Comment by josephspurrier** [comment]
Hi @danquack, you should be able to create compliance standards as well as query for them:

https://registry.terraform.io/providers/cloudtamer-io/cloudtamerio/latest/docs/resources/compliance_standard

```hcl
# Create a compliance standard.
resource "cloudtamerio_compliance_standard" "s1" {
  name               = "sample-resource"
  created_by_user_id = 1
  owner_users { id = 1 }
  owner_user_groups { id = 1 }
}

# Output the ID of the resource created.
output "standard_id" {
  value = cloudtamerio_compliance_standard.s1.id
}
```

**Comment by danquack** [comment]
Hmm not sure why I missed that! Thanks for the info!
